server:
  port: 8090


spring:
  r2dbc:
    url: "r2dbc:h2:mem:///MyDb"
    username: "aaa"
    password: "ppp"
  h2:
    console:
      enabled: true

application:
  usecase:
    newFlowEnabled : false
    feature:
      carLoan:
        isEnabled: true
      homeLoan:
        isEnabled: true
  interfaceadapters:
    feature:
      someFeature:
        someName: true

