CREATE TABLE IF NOT EXISTS Loan (LOAN_NUMBER SERIAL PRIMARY KEY, CUSTOMER_ID VARCHAR(255), PERIOD INTEGER, RATE DOUBLE,
PRINCIPLE DOUBLE, OUT_STANDING_LOAN_AMOUNT VARCHAR(255),
LOAN_TYPE VARCHAR(255), START_DATE TIMESTAMP, LOAN_STATUS VARCHAR(255), INITIAL_DISCOUNT_AMOUNT DOUBLE, LOAN_CREATED_SYSTEM VARCHAR(255));